package com.drone_command_center.Entity;

import com.drone_command_center.Entity.enums.WaypointAction;
import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import java.util.UUID;

@Entity
@Table(name = "waypoints")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Waypoint {

    @Id
    @GeneratedValue
    private UUID id;

    @NotNull(message = "Sequence order is required")
    @Min(value = 1, message = "Sequence order must be at least 1")
    @Column(nullable = false)
    private Integer sequenceOrder;

    @NotNull(message = "Latitude is required")
    @Min(value = -90, message = "Latitude must be between -90 and 90")
    @Max(value = 90, message = "Latitude must be between -90 and 90")
    @Column(nullable = false)
    private Double latitude;

    @NotNull(message = "Longitude is required")
    @Min(value = -180, message = "Longitude must be between -180 and 180")
    @Max(value = 180, message = "Longitude must be between -180 and 180")
    @Column(nullable = false)
    private Double longitude;

    @NotNull(message = "Altitude is required")
    @Min(value = 0, message = "Altitude must be at least 0")
    @Max(value = 10000, message = "Altitude must be less than 10000 meters")
    @Column(nullable = false)
    private Double altitude;

    // Speed to travel to this waypoint (m/s)
    @Min(value = 0, message = "Speed must be positive")
    @Max(value = 100, message = "Speed must be less than 100 m/s")
    private Double speed;

    // Time to hover at this waypoint (seconds)
    @Min(value = 0, message = "Hover duration must be positive")
    private Integer hoverDuration;

    // Action to perform at this waypoint
    @Enumerated(EnumType.STRING)
    private WaypointAction action;

    // Heading/yaw angle at this waypoint (degrees)
    @Min(value = 0, message = "Heading must be between 0 and 360")
    @Max(value = 360, message = "Heading must be between 0 and 360")
    private Double heading;

    // ─── NavRL NED waypoint coordinates (meters from origin) ───
    // For NAVIGATION/AUTONOMOUS_NAV missions, these are used instead of lat/lon
    // NavRL only uses [x, y] — altitude is reactive, speed is model-controlled
    private Double nedX;  // North position in meters
    private Double nedY;  // East position in meters

    // Whether this waypoint was generated by A* planner (vs manually set)
    private Boolean autoGenerated;

    // Associated mission
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mission_id", nullable = false)
    private Mission mission;
}
