package com.drone_command_center.DTO.response;

import com.drone_command_center.Entity.enums.WaypointAction;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WaypointDTO {
    
    private UUID id;
    private Integer sequenceOrder;
    private double latitude;
    private double longitude;
    private double altitude;
    private Double speed;
    private Integer hoverDuration;
    private WaypointAction action;
    private Double heading;

    // NavRL NED coordinates
    private Double nedX;
    private Double nedY;
    private Boolean autoGenerated;
}
