package com.drone_command_center.DTO.request;

import com.drone_command_center.Entity.enums.WaypointAction;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Request to create a waypoint")
public class WaypointCreateRequest {
    
    @NotNull(message = "Sequence order is required")
    @Min(value = 1, message = "Sequence order must be at least 1")
    @Schema(description = "Order of this waypoint in the mission", example = "1")
    private Integer sequenceOrder;
    
    @NotNull(message = "Latitude is required")
    @Min(value = -90, message = "Latitude must be between -90 and 90")
    @Max(value = 90, message = "Latitude must be between -90 and 90")
    @Schema(description = "Latitude coordinate", example = "37.7749")
    private Double latitude;
    
    @NotNull(message = "Longitude is required")
    @Min(value = -180, message = "Longitude must be between -180 and 180")
    @Max(value = 180, message = "Longitude must be between -180 and 180")
    @Schema(description = "Longitude coordinate", example = "-122.4194")
    private Double longitude;
    
    @NotNull(message = "Altitude is required")
    @Min(value = 0, message = "Altitude must be at least 0")
    @Max(value = 10000, message = "Altitude must be less than 10000 meters")
    @Schema(description = "Altitude in meters", example = "50.0")
    private Double altitude;
    
    @Min(value = 0, message = "Speed must be positive")
    @Max(value = 100, message = "Speed must be less than 100 m/s")
    @Schema(description = "Speed to travel to this waypoint (m/s)", example = "10.0")
    private Double speed;
    
    @Min(value = 0, message = "Hover duration must be positive")
    @Schema(description = "Time to hover at this waypoint (seconds)", example = "5")
    private Integer hoverDuration;
    
    @Schema(description = "Action to perform at this waypoint", example = "HOVER")
    private WaypointAction action;
    
    @Min(value = 0, message = "Heading must be between 0 and 360")
    @Max(value = 360, message = "Heading must be between 0 and 360")
    @Schema(description = "Heading/yaw angle at this waypoint (degrees)", example = "90.0")
    private Double heading;

    // NavRL NED waypoint coordinates
    @Schema(description = "NED X position - North (meters)", example = "25.0")
    private Double nedX;

    @Schema(description = "NED Y position - East (meters)", example = "-10.0")
    private Double nedY;

    @Schema(description = "Whether this waypoint was auto-generated by A* planner", example = "true")
    private Boolean autoGenerated;
}
